### ISSUE TITLE
[BUG] Claims not happening

### ISSUE THREAD

**Issue by KairuByte** [srhinos/primelooter#28]
❓**Describe the bug**
Claims are not happening, and the claimed/unclaimed list seems to be random. Errors are also showing in the logs.

📝**To Reproduce**
Just run the docker image.

🔎**Expected behavior**
For claims to happen.

☑️**Check List**
* [x]  I have attached a `primelooter.log` file to this issue
* [x]  I have searched the open issues for duplicates.

[primelooter.log](https://github.com/srhinos/primelooter/files/10044236/primelooter.log)

**Comment by srhinos** [comment]
resolved in #33
