### ISSUE TITLE
[BUG] module not found error

### ISSUE THREAD

**Issue by Gravitrax39** [srhinos/primelooter#45]
❓**Describe the bug**
when I open the command window and enter the start command it gives me
"Traceback (most recent call last):
  File "C:\Users\Gravi\OneDrive\Documents\primelooter-1.3.8\primelooter.py", line 8, in <module>
    from experiment import primelooter
  File "C:\Users\Gravi\OneDrive\Documents\primelooter-1.3.8\experiment.py", line 1, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'"

then nothing happens. it used to work perfectly fine then all the sudden changed to doing this.

📝**To Reproduce**
1. open command window
2. use command "python C:\Users\Gravi\OneDrive\Documents\primelooter-1.3.8\primelooter.py --cookies C:\Users\Gravi\OneDrive\Documents\primelooter-1.3.8\Paths\cookie.txt --publishers C:\Users\Gravi\OneDrive\Documents\primelooter-1.3.8\Paths\publishers.txt --loop"
3. See error
4. reverse profit

🔎**Expected behavior**
I expect it to load the looter as normal

☑️**Check List**
* I wasnt able to find where the primelooter.log file is, if you point me to it, ill add it

⚙️**Environment Details(please complete the following information):**
 - OS: Windows 10
 - Python Version:  3.11.5
 - Version: 1.3.8 (but was having the same issue on 1.3.7)

**Comment by Gravitrax39** [comment]
id add the "help wanted" label, but im not sure how to

**Comment by srhinos** [comment]
You need to install the dependencies from the requirements file as was noted in the readme. It changed a few weeks ago to actually work again. If you have further issues let me know!

**Comment by Gravitrax39** [comment]
ok I'm fairly certain that I have all the requirements installed, but I'm still running into the same problem. Also, I think I should mention that when I use the "python -m playwright install" command, it sits for a second and then nothing happens.

**Comment by srhinos** [comment]
> ok I'm fairly certain that I have all the requirements installed, but I'm still running into the same problem. Also, I think I should mention that when I use the "python -m playwright install" command, it sits for a second and then nothing happens.

There's no need to install playwright, it's not being used anymore. `python -m pip install -r requirements.txt` is what you wanna run

**Comment by Gravitrax39** [comment]
ok so after looking around, i used the command "python -m pip install httpx" and it started working
