### ISSUE TITLE
[FEAT] Docker compose/ container, just like the base repo?

### ISSUE THREAD

**Issue by GarnetSunset** [srhinos/primelooter#9]
The original Repo has a docker container etc. 

Can we get another docker container so I can run this on my home server easily :)

**Comment by macwilk** [comment]
This is already done! See the packages on this repo

**Comment by srhinos** [comment]
This is already done, see the generated image in the packages on this repo. Should work exactly the same as the old repo

**Comment by srhinos** [comment]
Just noticed I need to swap out the repo url in the docker compose. I did that! This should be doubly fixed now

**Comment by GarnetSunset** [comment]
Awesome, thank you!

**Comment by GarnetSunset** [comment]
The image container is giving me a 404 just fyi! :)

**Comment by srhinos** [comment]
> The image container is giving me a 404 just fyi! :)

have you pulled the repo since I've updated the image? Also could you paste me the full stack trace?

**Comment by srhinos** [comment]
I don't have docker installed on my windows pc so unfortunately can't test right now :(

**Comment by GarnetSunset** [comment]
Basically if you go to "ghcr.io/srhinos/primelooter:latest" in my browser, it appears to be private? I think... Not sure tbh...

**Comment by GarnetSunset** [comment]
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

https://github.com/srhinos/primelooter/blob/main/.github/workflows/release.yml#L32

**Comment by srhinos** [comment]
ah it defaults to private, changed to public. lemme know if that fixed it

**Comment by GarnetSunset** [comment]
Yes! It's fixed!! :)
